name: CD - Deploy to OCI VM

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to OCI VM
        env:
          SHA_SHORT: ${{ github.sha }}
        run: |
          IMAGE_TAG=$(echo $SHA_SHORT | cut -c1-7)

          ssh ubuntu@${{ secrets.OCI_HOST }} << EOF
            set -e

            cd ~/flight-delay-api

            export IMAGE_TAG=${IMAGE_TAG}

            echo "Deploying image tag: \$IMAGE_TAG"

            docker pull ghcr.io/wolganstark/flight-delay-api:\$IMAGE_TAG

            docker compose down
            docker compose up -d

            echo "Deployment completed"
          EOF
